# Generated by Django 5.0.6 on 2024-05-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='product_images/default.jpg', upload_to='product_images/'),
        ),
    ]
