# Generated by Django 5.0.6 on 2024-05-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='product_images/default_product.svg', upload_to='product_images/'),
        ),
    ]
