# Generated by Django 5.0.6 on 2024-06-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit', models.CharField(choices=[('oz', 'Ounce'), ('lbs', 'Pound'), ('Ct', 'None')], default='Ct', max_length=3)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('component_image', models.ImageField(blank=True, default='product_images/product_default4.svg', upload_to='product_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='product_images/product_default4.svg', upload_to='product_images/'),
        ),
    ]
