# Generated by Django 5.0.6 on 2024-06-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_component_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit',
            field=models.CharField(choices=[('oz', 'oz'), ('lbs', 'lbs'), ('Ct', 'ct')], default='Ct', max_length=3),
        ),
    ]
