# Generated by Django 5.0.6 on 2024-08-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dailysales_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
